# Terminal Hero Project Configuration
# This file documents the modular structure and dependencies

[project]
name = "terminal-hero"
version = "2.0.0"
language = "prolog"
implementation = "swi-prolog"
description = "A rhythm game inspired by Guitar Hero, running in the terminal"

[structure]
# Main entry point
main = "app/main.pl"

# Core modules
core_modules = [
    "src/terminal_hero.pl",      # Main game coordinator
    "src/game_config.pl",        # Game configuration
    "src/game_state.pl",         # State management
    "src/input_handler.pl",      # Input handling
    "src/display.pl",            # Rendering system
    "src/menu.pl"                # Menu system
]

# Asset modules
asset_modules = [
    "src/assets/title.pl"        # Visual assets
]

# Test modules
test_modules = [
    "tests/tests.pl"             # Test suite
]

[dependencies]
# SWI-Prolog standard libraries used
prolog_libraries = [
    "library(process)",          # For shell commands and process creation
    "library(random)",           # For random note generation
    "library(readutil)",         # For reading input
    "library(lists)"             # For list operations
]

[build]
# Build and run commands
run_command = "swipl -g main -t halt app/main.pl"
test_command = "swipl -g run_tests -t halt tests/tests.pl"
interactive_command = "swipl app/main.pl"

[compatibility]
# Backward compatibility
legacy_file = "terminal-hero.pl"
legacy_command = "swipl -g play -t halt terminal-hero.pl"
